# Generated by Django 4.0.2 on 2022-02-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0002_rename_img_mainimg_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст о себе')),
            ],
        ),
        migrations.AlterField(
            model_name='mainimg',
            name='photo',
            field=models.ImageField(upload_to='mainn/mainImg/', verbose_name='Фото для шапки сайта'),
        ),
    ]
