# Generated by Django 4.0.2 on 2022-02-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0005_vidsport'),
    ]

    operations = [
        migrations.CreateModel(
            name='VidGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('video', models.FileField(blank=True, upload_to='mainn/spv/', verbose_name='Видео')),
            ],
        ),
        migrations.CreateModel(
            name='VidOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('video', models.FileField(blank=True, upload_to='mainn/spv/', verbose_name='Видео')),
            ],
        ),
    ]
