# Generated by Django 4.0.2 on 2022-02-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0006_vidgame_vidother'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(blank=True, upload_to='mainn/blogImg/', verbose_name='Фото')),
                ('audio', models.FileField(blank=True, upload_to='mainn/blogmus', verbose_name='Музыка')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
            ],
        ),
    ]
